import type { Lead } from './types';

export const mockLeads: Lead[] = [
    {
        id: 'lead-001',
        name: 'Penzion U Vinohradu',
        accommodationType: 'Penzion',
        city: 'Mikulov',
        websiteOrOtaUrl: 'https://example.com/penzion-u-vinohradu',
        email: 'info@uvinohradu.example',
        status: 'Audit pripraven',
        notes: 'Rodinny penzion, silna sezonnost, vhodny pro rychly audit nabidky na OTA.',
        publicSignals: [
            'Fotografie pokoju jsou nekonzistentni mezi webem a OTA.',
            'Na hlavni strance chybi jasny duvod, proc rezervovat primo.',
            'Recenze casto zminuji snidane, ale web je neukazuje viditelne.',
        ],
        quickWins: [
            'Pridat blok s benefity prime rezervace.',
            'Sjednotit prvnich pet fotografii napric kanaly.',
            'Vytahnout snidane do prvni obrazovky webu.',
        ],
        publicProfileUrl: 'https://example.com/penzion-u-vinohradu',
        mainPhotoObservation: 'Hlavni fotka ukazuje exterier, ale malo prodava atmosferu pokoje nebo snidane.',
        betterPhotoSuggestion: 'Zvolit svetlou fotku pokoje se stolem, snidani nebo vyhledem, aby host hned videl hodnotu pobytu.',
        photoOrderObservation: 'Silnejsi fotky snidane a okoli jsou az pozdeji v galerii.',
        descriptionObservation: 'Popis je vecny, ale malo zduraznuje duvody, proc rezervovat primo.',
        reviewSignals: 'Hoste casto chvali snidane, klid a pristup personalu.',
        guestFrictionSignals: 'Neni hned jasne parkovani a presny postup prijezdu.',
        strengths: 'Silne pusobi lokalita, osobni atmosfera a pozitivni recenze na snidane.',
        risks: 'Dobry dojem muze byt slabsi, pokud host neuvidi nejvetsi vyhody uz v prvnich sekundach.',
        proposedQuickWins: [
            'Dat snidane nebo nejsvetlejsi pokoj do hlavni fotky.',
            'Presunout fotky pokoju, snidane a okoli do prvnich peti pozic.',
            'Doplnit kratky blok s parkovanim a benefitem prime rezervace.',
        ],
        selectedOfferAngle: 'main-photo',
        generatedMiniAudit: '',
        generatedOutreach:
            'Dobry den, vsiml jsem si nekolika rychlych prilezitosti, jak zlepsit prvni dojem hosta u vaseho penzionu. Rad vam poslu kratky mini-audit bez zavazku.',
        generatedFollowUp: '',
        generatedOffer: '',
        lastContactDate: '',
        nextFollowUpDate: '2026-05-13',
    },
    {
        id: 'lead-002',
        name: 'Apartmany Pod Hradem',
        accommodationType: 'Apartman',
        city: 'Cesky Krumlov',
        websiteOrOtaUrl: 'https://example.com/apartmany-pod-hradem',
        email: 'rezervace@podhradem.example',
        status: 'Novy',
        notes: 'Dobre hodnoceni, slabsi prezentace dlouhodobych pobytu.',
        publicSignals: [
            'OTA profil ma vysoke hodnoceni lokality.',
            'Web nema jasne CTA pro dotaz na dostupnost.',
        ],
        quickWins: [
            'Zvyraznit lokalitu a parkovani v uvodu.',
            'Pridat jednoduche CTA pro prime poptavky.',
        ],
        publicProfileUrl: 'https://example.com/apartmany-pod-hradem',
        mainPhotoObservation: '',
        betterPhotoSuggestion: '',
        photoOrderObservation: '',
        descriptionObservation: '',
        reviewSignals: 'Recenze zminuji lokalitu a cistotu.',
        guestFrictionSignals: '',
        strengths: 'Vyborna lokalita a dobre hodnoceni cistoty.',
        risks: '',
        proposedQuickWins: [
            'Zvyraznit lokalitu a parkovani v uvodu.',
            'Pridat jednoduche CTA pro prime poptavky.',
            'Doplnit pro koho jsou apartmany idealni.',
        ],
        selectedOfferAngle: 'description',
        generatedMiniAudit: '',
        generatedOutreach: '',
        generatedFollowUp: '',
        generatedOffer: '',
        lastContactDate: '',
        nextFollowUpDate: '',
    },
];