import type { Lead } from './types';

export const mockLeads: Lead[] = [
    {
        id: 'lead-001',
        name: 'Penzion U Vinohradu',
        accommodationType: 'Penzion',
        city: 'Mikulov',
        websiteOrOtaUrl: 'https://example.com/penzion-u-vinohradu',
        email: 'info@uvinohradu.example',
        status: 'Audit pripraven',
        notes: 'Rodinny penzion, silna sezonnost, vhodny pro rychly audit nabidky na OTA.',
        publicSignals: [
            'Fotografie pokoju jsou nekonzistentni mezi webem a OTA.',
            'Na hlavni strance chybi jasny duvod, proc rezervovat primo.',
            'Recenze casto zminuji snidane, ale web je neukazuje viditelne.',
        ],
        quickWins: [
            'Pridat blok s benefity prime rezervace.',
            'Sjednotit prvnich pet fotografii napric kanaly.',
            'Vytahnout snidane do prvni obrazovky webu.',
        ],
        publicProfileUrl: 'https://example.com/penzion-u-vinohradu',
        publicLinks: [
            {
                id: 'link-001-booking',
                sourceType: 'booking',
                url: 'https://example.com/penzion-u-vinohradu',
                label: 'OTA profil',
                notes: 'Demo link pro rucni verejnou kontrolu.',
            },
            {
                id: 'link-001-web',
                sourceType: 'website',
                url: 'https://example.com/penzion-u-vinohradu-web',
                label: 'Vlastni web',
                notes: 'Porovnani s OTA prezentaci.',
            },
        ],
        firstImpression: 'Nabidka pusobi duveryhodne diky lokalite a recenzim, ale nejsilnejsi argumenty jsou rozptylene mezi fotkami, textem a recenzemi.',
        mainPhotoVerdict: 'average',
        mainPhotoObservation: 'Hlavni fotka ukazuje exterier, ale malo prodava atmosferu pokoje nebo snidane.',
        betterPhotoSuggestion: 'Zvolit svetlou fotku pokoje se stolem, snidani nebo vyhledem, aby host hned videl hodnotu pobytu.',
        photoOrderObservation: 'Silnejsi fotky snidane a okoli jsou az pozdeji v galerii.',
        descriptionObservation: 'Popis je vecny, ale malo zduraznuje duvody, proc rezervovat primo.',
        checkInParkingInfo: 'Parkovani a prijezd nejsou videt v prvnim bloku textu, i kdyz jsou pro hosta pred rezervaci prakticky dulezite.',
        reviewSignals: 'Hoste casto chvali snidane, klid a pristup personalu.',
        guestFrictionSignals: 'Neni hned jasne parkovani a presny postup prijezdu.',
        guestConfusion: 'Host muze rychle pochopit, ze penzion je prijemny, ale nemusi hned vedet, proc rezervovat primo a jak bude reseny prijezd.',
        strengths: 'Silne pusobi lokalita, osobni atmosfera a pozitivni recenze na snidane.',
        risks: 'Dobry dojem muze byt slabsi, pokud host neuvidi nejvetsi vyhody uz v prvnich sekundach.',
        businessOpportunity: 'Nejrychlejsi prilezitost je vytahnout snidane, parkovani a benefit prime rezervace do prvnich sekund rozhodovani.',
        proposedQuickWins: [
            'Dat snidane nebo nejsvetlejsi pokoj do hlavni fotky.',
            'Presunout fotky pokoju, snidane a okoli do prvnich peti pozic.',
            'Doplnit kratky blok s parkovanim a benefitem prime rezervace.',
        ],
        structuredQuickWins: [
            {
                id: 'quick-win-001-1',
                title: 'Ukazat snidane driv',
                why: 'Recenze snidane chvali, ale host je nevidi jako jeden z prvnich argumentu.',
                action: 'Presunout fotku snidane nebo svetleho pokoje do prvnich peti fotek a zminit snidane v prvnim odstavci.',
                sourceEvidence: 'Recenze chvali snidane; silnejsi fotky snidane jsou az pozdeji v galerii.',
            },
            {
                id: 'quick-win-001-2',
                title: 'Zviditelnit parkovani a prijezd',
                why: 'Host pred rezervaci potrebuje rychle pochopit prakticke podminky prijezdu.',
                action: 'Doplnit kratky blok s parkovanim a prijezdem do horni casti popisu.',
                sourceEvidence: 'Parkovani a prijezd nejsou videt v prvnim bloku textu.',
            },
            {
                id: 'quick-win-001-3',
                title: 'Vysvetlit duvod prime rezervace',
                why: 'Vlastni web zatim malo rika, proc by host nemel rezervovat pres OTA.',
                action: 'Pridat kratky benefit prime rezervace vedle CTA: napr. rychlejsi potvrzeni nebo jasne podminky.',
                sourceEvidence: 'Popis malo zduraznuje duvody, proc rezervovat primo.',
            },
        ],
        selectedOfferAngle: 'main-photo',
        generatedMiniAudit: '',
        generatedOutreach:
            'Dobry den, vsiml jsem si nekolika rychlych prilezitosti, jak zlepsit prvni dojem hosta u vaseho penzionu. Rad vam poslu kratky mini-audit bez zavazku.',
        generatedFollowUp: '',
        generatedOffer: '',
        lastContactDate: '',
        nextFollowUpDate: '2026-05-13',
    },
    {
        id: 'lead-002',
        name: 'Apartmany Pod Hradem',
        accommodationType: 'Apartman',
        city: 'Cesky Krumlov',
        websiteOrOtaUrl: 'https://example.com/apartmany-pod-hradem',
        email: 'rezervace@podhradem.example',
        status: 'Novy',
        notes: 'Dobre hodnoceni, slabsi prezentace dlouhodobych pobytu.',
        publicSignals: [
            'OTA profil ma vysoke hodnoceni lokality.',
            'Web nema jasne CTA pro dotaz na dostupnost.',
        ],
        quickWins: [
            'Zvyraznit lokalitu a parkovani v uvodu.',
            'Pridat jednoduche CTA pro prime poptavky.',
        ],
        publicProfileUrl: 'https://example.com/apartmany-pod-hradem',
        publicLinks: [
            {
                id: 'link-002-web',
                sourceType: 'website',
                url: 'https://example.com/apartmany-pod-hradem',
                label: 'Vlastni web',
                notes: 'Demo link pro rucni verejnou kontrolu.',
            },
        ],
        firstImpression: 'Nabidka komunikuje lokalitu a cistotu, ale mene jasne ukazuje, pro koho jsou apartmany nejvhodnejsi.',
        mainPhotoVerdict: 'unknown',
        mainPhotoObservation: '',
        betterPhotoSuggestion: '',
        photoOrderObservation: '',
        descriptionObservation: '',
        checkInParkingInfo: '',
        reviewSignals: 'Recenze zminuji lokalitu a cistotu.',
        guestFrictionSignals: '',
        guestConfusion: 'Host vidi dobrou lokalitu, ale rychle neziska jasny scenar pobytu ani duvod k primemu dotazu.',
        strengths: 'Vyborna lokalita a dobre hodnoceni cistoty.',
        risks: '',
        businessOpportunity: 'Zpresnit text pro hosty, kteri hledaji pohodlny pobyt v centru a chteji rychle overit dostupnost.',
        proposedQuickWins: [
            'Zvyraznit lokalitu a parkovani v uvodu.',
            'Pridat jednoduche CTA pro prime poptavky.',
            'Doplnit pro koho jsou apartmany idealni.',
        ],
        structuredQuickWins: [
            {
                id: 'quick-win-002-1',
                title: 'Zpresnit idealniho hosta',
                why: 'Silna lokalita bude presvedcivejsi, kdyz host hned pozna, pro jaky typ pobytu je nabidka nejlepsi.',
                action: 'Doplnit jednu vetu pro pary, rodiny nebo hosty na kratky pobyt podle realne nejsilnejsi skupiny.',
                sourceEvidence: 'Web nema jasne CTA pro dotaz na dostupnost a text mene rika, pro koho jsou apartmany idealni.',
            },
        ],
        selectedOfferAngle: 'description',
        generatedMiniAudit: '',
        generatedOutreach: '',
        generatedFollowUp: '',
        generatedOffer: '',
        lastContactDate: '',
        nextFollowUpDate: '',
    },
];